# **Activity 1: NumPy Exercise**

**Objective:**

Practice NumPy's array manipulation, indexing, and mathematical functions by solving problems related to basic data analysis and matrix operations.

# Earl Geibriel S. Dicipulo


## **Part 1**

#### 1. Import the numpy package under the name `np`


In [5]:
import numpy as np

#### 2. Print the numpy version

In [4]:
print(np.__version__)

2.2.2


#### 3. Create a null array of size 5

In [8]:
import numpy as np

arr = np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


#### 4. Create a null array of size 15 but the seventh value which is 1

In [9]:
import numpy as np

arr = np.zeros(15)
arr[6] = 1

print(arr)

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 5. Create a 4x4 matrix with values ranging from 0 to 11

In [17]:
import numpy as np

arr = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
newarr = arr.reshape(4,4)

print(newarr)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 6. Find indices of non-zero elements from [1,2,4,0,4,0]

In [18]:
import numpy as np


arr = np.array([1,2,4,0,4,0])
x = np.where(arr != 0)

print(x)

(array([0, 1, 2, 4]),)


#### 7. Create a 4x4x4 array with random values

In [20]:
import numpy as np

arr = np.random.randint(100, size=(4,4,4))
print(arr)


[[[71 22 83  2]
  [96 85 42 22]
  [65 98 25 86]
  [ 8 50 59  3]]

 [[42 64 63 71]
  [ 9 96  5 27]
  [59 58 10  6]
  [67 58 37 17]]

 [[55 49 74 59]
  [41 82 28 84]
  [68 56  8 31]
  [94 35 12 19]]

 [[ 4 45 15 35]
  [49 30  5 37]
  [74 22 41 29]
  [60 57 88 88]]]


#### 8. Create a 15x15 array with random assigned values and find the min and max values

In [22]:
import numpy as np

arr = np.random.randint(225, size=(15,15))
min = np.min(arr)
max = np.max(arr)

print(arr)
print('Minimum Value: ', min)
print('Maximum Value: ', max)

[[122 120 195 200 158 116  33  73 166  66   9 151 204  58  66]
 [  9 198  53  65 161 172 206 173 206  75  16 138 142 201 166]
 [165 103  31 120  38  97 132  65  82 138 170  38 223  70  90]
 [  9  19 175  91 119  31 138  52   4 146 135  85 103  83 118]
 [  1 162  72  22  70 121  97 129 102 162  32 116  29  61  42]
 [220 173   1  22  91  39 193  74  80 152  47   1 201 200 115]
 [162  29  30 182  63 117  46 181 214  98 186  73  89 217 133]
 [117 195  34  85 139 195 160 155  69 101  26 160 124   4 173]
 [117 148  39  52 190 105   9 150  26 139  51 206 154  77  80]
 [172  92 135 201 136 113  53  66 187  77 108  18  70 187 111]
 [ 93  71  80  53 166 181  92  72 169 101  53 215  99  47 168]
 [104  20  21  37  48 165 131 129 167  62  43 206  27 197 176]
 [219 170  84  29 137 142  46 214 134   4  66 208  40 183 183]
 [128  33 142  46  92 185  78 171  21  25  38 115 171  36 104]
 [193 190  37 196  16 206  54 201 195  68 138 141 116 142 167]]
Minimum Value:  1
Maximum Value:  223


#### 9. Create a random array of size 25 and find the mean value

In [24]:
import numpy as np

arr = np.random.randint(625, size=(25))
mean = np.mean(arr)

print(arr)
print('Mean of array: ', mean)

[131 381 262 349 529  39 530 323 158 335 126 140 404 130 250 438 574  11
  82  88  37 491 441   4 383]
Mean of array:  265.44


#### 10.  Show your codes

Given:

array 1 = ([2, 4, 9])\
array 2 = ([1, 14, 6])

  *Note: Recreate the arrays*

In [25]:
import numpy as np

arr1 = np.array([2,4,9])
arr2 = np.array([1,14,6])

print(arr1, arr2)

[2 4 9] [ 1 14  6]


10.1 What is the result of *a + b*?

In [28]:
import numpy as np

arr1 = np.array([2,4,9])
arr2 = np.array([1,14,6])

newarr = np.add(arr1, arr2)

print(newarr)

[ 3 18 15]


10.2 What is the result of *a - b*?

In [29]:
import numpy as np

arr1 = np.array([2,4,9])
arr2 = np.array([1,14,6])

newarr = np.subtract(arr1, arr2)

print(newarr)

[  1 -10   3]


10.3 What is the result of *a × b*?

In [30]:
import numpy as np

arr1 = np.array([2,4,9])
arr2 = np.array([1,14,6])

newarr = np.multiply(arr1, arr2)

print(newarr)

[ 2 56 54]


10.4 What is the result of *a ÷ b*?

In [31]:
import numpy as np

arr1 = np.array([2,4,9])
arr2 = np.array([1,14,6])

newarr = np.divide(arr1, arr2)

print(newarr)

[2.         0.28571429 1.5       ]


## **Part 2**

##### NumPy Array Indexing


Given the following matrix:

        [[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]]

 1. Recreate the matrix

In [34]:
import numpy as np

arr = np.array([[10,20,30],[40,50,60],[70,80,90]])

print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


1. Write code to extract the element 50.

In [42]:
import numpy as np

arr = np.array([[10,20,30],[40,50,60],[70,80,90]])

print(arr[1,1])

50


2. **Extract a Row**\
\
Using the same array arr, extract the second row as a separate NumPy array.

In [44]:
import numpy as np

arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
row_arr = arr[1]

print(row_arr)



[40 50 60]


3.  **Extract a Column**\
\
Using arr, extract the third column as a separate NumPy array.

In [46]:
import numpy as np

arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
col_arr = arr[:, 2]

print(col_arr)

[30 60 90]


4. **Extract a Submatrix**\
\
Extract the following 2×2 submatrix from arr:\

  [[50 60]\
 [80 90]]

In [47]:
import numpy as np

arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
submatrix = arr[1:3, 1:3]

print(submatrix)

[[50 60]
 [80 90]]


##### NumPy Array Slicing

Given the following matrix:

                [ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12]]

1. Recreate the matrix

In [48]:
import numpy as np

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2. Write code to extract the following 2×2 subarray:

        [[ 6  7]
        [10 11]]

In [49]:
import numpy as np

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
subarray = arr[1:3, 1:3]

print(subarray)

[[ 6  7]
 [10 11]]


3. Using the same matrix, write code to extract every other element from the first row (expected output: [1, 3]).

In [52]:
import numpy as np

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
newarr = arr[0, ::2]

print(newarr)

[1 3]


4. Write code to reverse the order of rows in the matrix

In [53]:
import numpy as np

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
newarr = arr[::-1]

print(newarr)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


5. Write code to extract the last two columns of the matrix.

In [59]:
import numpy as np

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
newarr = arr[:, 2:4]

print(newarr)

[[ 3  4]
 [ 7  8]
 [11 12]]


##### NumPy Array Joins

1. Given the following arrays:

        arr1 = ([11, 7, 33])\
        arr2 = ([44, 5, 18])

1.1 Recreate the arrays

In [60]:
import numpy as np

arr1 = np.array([11,7,33])
arr2 = np.array([44,5,18])

print(arr1, arr2)

[11  7 33] [44  5 18]


2. Write code to join arr1 and arr2 into a single 1D array.

In [61]:
import numpy as np

arr1 = np.array([11,7,33])
arr2 = np.array([44,5,18])

newarr = np.concatenate((arr1, arr2))

print(newarr)

[11  7 33 44  5 18]


3. Using arr1 and arr2 from question 1, write code to stack them vertically into a 2D array.

In [62]:
import numpy as np

arr1 = np.array([11,7,33])
arr2 = np.array([44,5,18])

newarr = np.vstack((arr1, arr2))

print(newarr)


[[11  7 33]
 [44  5 18]]


4. Given the 2D arrays:

        arr1 = ([[1, 2],
               [3, 4]])

        arr2 = ([[5, 6],
               [7, 8]])

4.1 Recreate the arrays

In [63]:
import numpy as np

arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

print(arr1, arr2)

[[1 2]
 [3 4]] [[5 6]
 [7 8]]


5. Write code to join them horizontally (column-wise).

In [64]:
import numpy as np

arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

newarr = np.hstack((arr1, arr2))

print(newarr)

[[1 2 5 6]
 [3 4 7 8]]


6. Using arr1 and arr2 from question 4, write code to join them vertically (row-wise).


In [65]:
import numpy as np

arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

newarr = np.vstack((arr1, arr2))

print(newarr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## **Part 3**

### Task 1: Array Creation

Create the following arrays:

- A 1D array of integers from 10 to 28, with a step of 2.
- A 2D array with shape (4, 4) containing random integers between 1 and 50.
- A 3D array of shape (2, 3, 4) filled with ones.



In [76]:
import numpy as np

arr1 = np.arange(10,29,2)
arr2 = np.random.randint(50, size=(4,4))
arr3 = np.full((2,3,4), 1)

print(arr1, '\n')
print(arr2, '\n')
print(arr3)

[10 12 14 16 18 20 22 24 26 28] 

[[47 49 14 27]
 [15 12 15  9]
 [ 6 31 43 39]
 [40  8 27 47]] 

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


### Task 2: Array Transformations
Perform the following operations:
- Reshape the 1D array to a 2D array with 2 rows.
- Extract the last two rows of the 2D array (From Task 1)
- Replace all even numbers in the 2D array with -1. (From Task 1)

In [110]:
import numpy as np

arr1 = np.arange(10,29,2)
arr2 = np.random.randint(50, size=(4,4))
arr3 = np.full((2,3,4), 1)


newarr1 = np.vstack((arr1, arr1))
newarr2 = arr2[:, 2]

arr2[arr2%2 == 0] = -1

print(newarr1, '\n')
print(newarr2, '\n')    
print(arr2)



[[10 12 14 16 18 20 22 24 26 28]
 [10 12 14 16 18 20 22 24 26 28]] 

[-1 -1 -1 23] 

[[ 7 43 -1 39]
 [-1 -1 -1 -1]
 [41 -1 -1 27]
 [31 -1 23 17]]


### Task 3: Statistical Operations

Using the 2D array from **Task 1**, compute the following:

- The mean, median, and standard deviation of the array. (From Task 1)
- The sum of all elements along each row. (From Task 1)
- The maximum value and its index in the entire array. (From Task 1)


In [145]:
import numpy as np

arr2 = np.random.randint(50, size=(4,4))

# Find Mean, Median, Standard Deviation
mean = np.mean(arr2)
median = np.median(arr2)
standard_deviation = np.std(arr2)
print('\n')

# Find sum of all elements along each row
sum_arr = np.sum(arr2, axis=1).tolist()

# Find maximum value and its index
max_val = np.max(arr2)
max_val_index = np.where(arr2 == np.max(arr2))

print(arr2, '\n')

print('Mean: ', mean)
print('Median: ', median)
print('Standard Deviation: ', standard_deviation, '\n')

print(sum_arr, '\n')

print('Maximum Value of Array: ', max_val)
print('Index of Maximum Value:', max_val_index)



[[15 19 21 46]
 [ 2 14 42 46]
 [15 35 27  7]
 [38 31 47 49]] 

Mean:  28.375
Median:  29.0
Standard Deviation:  14.966107543379474 

[101, 104, 84, 165] 

Maximum Value of Array:  49
Index of Maximum Value: (array([3]), array([3]))


###  Task 4: Advanced Analysis on Large Arrays

- Create a (10, 10) array containing random floating-point numbers between 0 and 1.
- Find the minimum value along each column.
- Find the indices of the top 5 largest values in the entire array.

In [151]:
import numpy as np

arr = np.random.rand(10,10)

print(arr, '\n')

print('Minimum value along each column:')
for x in range(4):
    print(np.min(arr[x,:]))
    
print('\nIndices of the top 5 largest values in the array:')

int_indices = np.argpartition(arr.flatten(), -5)[-5:]
print(np.unravel_index(int_indices, arr.shape))
    

    




[[0.35847582 0.39760491 0.97103657 0.67566176 0.12389446 0.0717101
  0.27720686 0.37234284 0.84585577 0.6225075 ]
 [0.41459599 0.55535506 0.8071126  0.43858028 0.55044032 0.54564047
  0.77133273 0.39325689 0.6189018  0.69736431]
 [0.57603825 0.33078464 0.5379036  0.74351755 0.14939607 0.86915854
  0.17780884 0.76269061 0.38204942 0.70847511]
 [0.22548466 0.53798982 0.62909408 0.90920592 0.02964842 0.38175567
  0.24162999 0.15057797 0.56674339 0.46350288]
 [0.20169102 0.68948288 0.89214547 0.73294592 0.66099226 0.27644999
  0.93027006 0.81892773 0.48295755 0.52179483]
 [0.7230353  0.36306663 0.40731337 0.71412871 0.86662729 0.44079069
  0.91522898 0.34775227 0.09261511 0.90422817]
 [0.75741982 0.51698308 0.220951   0.87751549 0.25371527 0.81163854
  0.53962385 0.57090049 0.47312454 0.69516742]
 [0.13373457 0.38438373 0.28119596 0.89116364 0.35604626 0.63906195
  0.70669722 0.78269768 0.43853813 0.72189902]
 [0.95604202 0.97178922 0.6331423  0.64583881 0.81951414 0.67315274
  0.1806652  